name: 'gitStream repo agent'
description: 'Public GitHub action for gitStream Continuous Merge'
inputs:
  full_repository:
    description: 'Path of full Repository'
    required: true
  head_ref:
    description: 'Head Branch Ref to checkout to'
    required: true
  base_ref:
    description: 'Base Branch Ref to checkout to'
    required: true
  client_payload:
    description: 'The client payload'
    required: true
  installation_id:
    description: 'The github app installation id'
    required: false
  resolver_url:
    description: 'Resolver url to send results to'
    required: true
  resolver_token:
    description: 'Optional token for resolver'
    required: false
  debug_mode:
    description: 'Run parser in debug mode'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Set start time
      id: start
      run: echo "timestamp=$EPOCHSECONDS" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Docker image
      id: cache-docker
      uses: actions/cache@v3
      with:
        path: rule-engine
        key: rule-engine

    - name: Cache gitstream folder
      id: cache-gitstream
      uses: actions/cache@v3
      with:
        path: gitstream
        key: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).repo }}-${{ github.event.inputs.head_ref }}-gitsream-cache

    - name: Create GitStream folder
      id: create-gitstream-folder
      shell: bash
      run: |
        mkdir gitstream
        cd gitstream
        mkdir repo
    - name: Checkout head branch
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.full_repository }}
        ref: ${{ github.event.inputs.head_ref }}
        path: 'gitstream/repo/'
        clean: false
        token: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).githubToken || github.token }}
    - run: |
        all=2147483647
        cd gitstream
        cd repo
        git fetch --deepen=$all origin ${{ github.event.inputs.base_ref }}
        git checkout -b ${{ github.event.inputs.base_ref }} origin/${{ github.event.inputs.base_ref }}
        git checkout ${{ github.event.inputs.head_ref }}
        git fetch --deepen=$all origin ${{ github.event.inputs.head_ref }}
      shell: bash
    - name: Create cm folder
      id: create-cm-folder
      shell: bash
      run: |
        cd gitstream
        mkdir cm
    - name: Checkout cm repo
      uses: actions/checkout@v3
      ## this step will be skipped if cache exists AND has cm repo
      if: ${{ fromJSON(github.event.inputs.client_payload).hasCmRepo == true }}
      with:
        repository: '${{ fromJSON(fromJSON(github.event.inputs.client_payload)).owner }}/${{ fromJSON(fromJSON(github.event.inputs.client_payload)).cmRepo }}'
        ref: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).cmRepoRef }}
        path: 'gitstream/cm/'
        clean: false

    - name: Load cache docker
      id: load-docker
      if: ${{ steps.cache-docker.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        docker load -i rule-engine/rules-engine.tar

    - name: Pull Rule engine
      id: pull-rule-engine
      shell: bash
      if: ${{ steps.cache-docker.outputs.cache-hit != 'true' }}
      run: |
        SECONDS=0
        docker pull gitstream/rules-engine:latest
        echo "docker-pull-duration=$SECONDS" >> $GITHUB_OUTPUT

    - name: Run The Action
      id: gitstream-action
      if: always()
      run: |
        SECONDS=0
        docker run -v $(pwd)/gitstream:/code -e HEAD_REF=${{ github.event.inputs.head_ref }} -e BASE_REF=${{ github.event.inputs.base_ref }} -e CLIENT_PAYLOAD=${{ github.event.inputs.client_payload }} -e RULES_RESOLVER_URL=${{ github.event.inputs.resolver_url }} -e RULES_RESOLVER_TOKEN=${{ github.event.inputs.resolver_token }} -e DEBUG_MODE=${{ github.event.inputs.debug_mode }} gitstream/rules-engine
        echo "docker-run-duration=$SECONDS" >> $GITHUB_OUTPUT
        echo "action-run-duration=$(($EPOCHSECONDS - ${{ steps.start.outputs.timestamp }}))" >> $GITHUB_OUTPUT
      shell: bash

    - name: save-docker
      if: ${{ steps.cache-docker.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        mkdir rule-engine
        docker save gitstream/rules-engine:latest -o rule-engine/rules-engine.tar
